[project]
name = "copilotmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.3.1",
    "mcp[cli]>=1.8.0",
    "starlette[standard]>=0.46.2",
    "uvicorn[full,standard]>=0.34.2",
]
